#! /bin/bash

DESCRIPTOR=$1
LXC_PATH=$2

function check_dev_type {
if [[ $DEVPATH == *drm* ]]; then
        DEVTYPE=dri
fi
if [[ $DEVPATH == *sound* ]]; then
        DEVTYPE=snd
fi
if [[ $DEVPATH == *input* ]]; then
        DEVTYPE=input
fi
if [[ $DEVPATH == *tty* ]]; then
        DEVTYPE=.
fi }

for dev_candidate in /dev/char/*
do
        if [[ "echo $( udevadm info -q path -n $dev_candidate )" == *$DESCRIPTOR* ]]; then

                MAJOR="$(echo $dev_candidate |cut -d "/" -f4 |cut -d ":" -f1)"
                MINOR="$(echo $dev_candidate |cut -d "/" -f4 |cut -d ":" -f2)"
                DEVPATH="$( udevadm info -q path -n $dev_candidate )"
                DEVNAME="$(echo $DEVPATH | grep -oE "[^/]+$" )"

                check_dev_type

                echo "mkdir -p $DEVTYPE" >> $LXC_PATH/autodev.temp
                echo "mknod -m 0666 $DEVTYPE/$DEVNAME c $MAJOR $MINOR" >> $LXC_PATH/autodev.temp
                echo "lxc.cgroup.devices.allow = c $MAJOR:$MINOR rwm # $DEVNAME" >> $LXC_PATH/config.temp
        fi
done
