#! /bin/bash

# Checking arguments
if [[ $# -lt 2 ]]; then
     echo "Please provide the proper arguments. Ie: # usbdriver ID autobind/unbind/info"
     exit 1
fi

# Getting USB data
USBID=$(echo `lsusb.py -U |grep $1`|cut -d " " -f2)
BUSUSB=$(echo `lsusb.py -U |grep $1`|cut -d " " -f1)

# Check if the USB exists
if [[ ! -e /sys/bus/usb/devices/$BUSUSB/uevent ]]; then
     echo The $1 is not a valid expresion for the USB, check lsusb.py as root
     exit 1
fi

# Parse the second argument
case $2 in
unbind)
     if [[ -e /sys/bus/usb/devices/$BUSUSB/driver/unbind ]]; then
          echo Unbinding $(lsusb -d $USBID)
          echo $BUSUSB |cut -d "/" -f6 > /sys/bus/usb/devices/$BUSUSB/driver/unbind
     else
          echo $(lsusb -d $USBID) was already unbound
     fi
;;
autobind)
     if [[ ! -e /sys/bus/usb/devices/$BUSUSB/driver/bind ]]; then
          echo $BUSUSB |cut -d "/" -f6 > /sys/bus/usb/drivers_probe
          echo Binding $(lsusb -d $USBID) as $(cat /sys/bus/usb/devices/$BUSUSB/uevent |grep DRIVER |cut -d "=" -f2)
     else
          echo $(lsusb -d $USBID) was already bound
     fi
;;
info)
     echo $(lsusb -d $USBID)
     echo Used USB port $BUSUSB
     echo USB ID $USBID
     findudev $BUSUSB
;;
esac
