version: '3.6'

services:
  freeipa:
    #image: freeipa/freeipa-server
    image: index.docker.io/freeipa/freeipa-server:centos-7    
    hostname: ipa.londres.casa
    network_mode: "host"
    #cap_add:
      #- NET_ADMIN
      #- SYS_ADMIN
    environment:
      IPA_SERVER_IP: 192.168.1.160
      TZ: Europe/Madrid
      #DEBUG_TRACE: 1
      #DEBUG_NO_EXIT: 1
    #ports:
      # FreeIPA WebUI
     # - "80:80"
      #- "443:443"
      # Kerberos
      #- "88:88/udp"
      #- "88:88"
      #- "464:464/udp"
      #- "464:464"
      # LDAP
      #- "389:389"
      #- "636:636"
      # DNS
      #- "53:53/udp"
      #- "53:53"
      # NTP
      #- "123:123/udp"
      # Ni idea
      #- "7389:7389"
      #- "9443:9443"
      #- "9444:9444"
      #- "9445:9445"
    extra_hosts:
      - "londres.casa ipa:192.168.1.160"
      - "localhost:127.0.0.1"
      - "lo:::1"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - freeipa_data:/data:Z
    command: ipa-server-install -r LONDRES.CASA -n ipa.londres.casa -p FLXfbi82.. -a FLXfbi82.. --hostname ipa.londres.casa -U

volumes:
  freeipa_data:
