version: '3'

services:
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:


docker run -d \
    --name portainer \
    --label traefik.backend=portainer \
    --label traefik.port=9000 \
    --label traefik.frontend.rule="Host:portainer.londres.casa" \
    --label traefik.frontend.entryPoints=http \
    -p 9000:9000 \
    --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer
